version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - aps_posts
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    image: allyotov/aps_posts:1.0.0
    networks:
      - aps_posts
    env_file: .env
    volumes:
      - ./backend_data:/data

networks:
  aps_posts: