version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - searchapp
    env_file: 
      - .env
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:8.2.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    env_file:
      - .env
    volumes:
      - ./.data/dev_es_data:/usr/share/elasticsearch/data
    networks:
      - searchapp
    ports:
      - 9200:9200

networks:
  searchapp: