version: '3.7'
services:
  post_db:
    image: postgres:14.0
    networks:
      - aps_posts
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  post_backend:
    image: allyotov/aps_posts:latest
    networks:
      - aps_posts
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - ./backend_data:/data

networks:
  aps_posts: